### ISSUE TITLE
basically instacrash on b1.6.6

### ISSUE THREAD

**Issue by arceuss** [ViaVersionAddons/ViaProxyBeta2Release#4]
client gives `java.lang.NullPointerException: Cannot invoke "un.c()" because "<local19>" is null
	at di.a(SourceFile:169)
	at m.a(SourceFile:1132)
	at pt.a(SourceFile:621)
	at pt.b(SourceFile:511)
	at net.minecraft.client.Minecraft.run(SourceFile:743)
	at java.base/java.lang.Thread.run(Thread.java:833)`
	
and viaproxy just gives `[21:50:31] [Netty NIO Server Child IO #8/INFO] (LoggerPrintStream) [STDERR]: java.net.SocketException: Connection reset
[21:50:31] [Netty NIO Server Child IO #8/INFO] (LoggerPrintStream) [STDERR]:    at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:401)
[21:50:31] [Netty NIO Server Child IO #8/INFO] (LoggerPrintStream) [STDERR]:    at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:434)
[21:50:31] [Netty NIO Server Child IO #8/INFO] (LoggerPrintStream) [STDERR]:    at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:255)
[21:50:31] [Netty NIO Server Child IO #8/INFO] (LoggerPrintStream) [STDERR]:    at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
[21:50:31] [Netty NIO Server Child IO #8/INFO] (LoggerPrintStream) [STDERR]:    at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:356)
[21:50:31] [Netty NIO Server Child IO #8/INFO] (LoggerPrintStream) [STDERR]:    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151)
[21:50:31] [Netty NIO Server Child IO #8/INFO] (LoggerPrintStream) [STDERR]:    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
[21:50:31] [Netty NIO Server Child IO #8/INFO] (LoggerPrintStream) [STDERR]:    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
[21:50:31] [Netty NIO Server Child IO #8/INFO] (LoggerPrintStream) [STDERR]:    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
[21:50:31] [Netty NIO Server Child IO #8/INFO] (LoggerPrintStream) [STDERR]:    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
[21:50:31] [Netty NIO Server Child IO #8/INFO] (LoggerPrintStream) [STDERR]:    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994)
[21:50:31] [Netty NIO Server Child IO #8/INFO] (LoggerPrintStream) [STDERR]:    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[21:50:31] [Netty NIO Server Child IO #8/INFO] (LoggerPrintStream) [STDERR]:    at java.base/java.lang.Thread.run(Thread.java:1583)`

if it helps i am connecting to a server that is on 1.20.4, it works fine when i connect from b1.7.3 (haven't tested below b1.6 cuz i'm lazy)

**Comment by RaphiMC** [comment]
Beta2Release only supports beta 1.7.3, so connecting with any other beta version won't work
